@startuml

Пользователь -up-> (Авторизация)
Пользователь -up-> (Выход)
Пользователь -up-> (Регистрация)

Пользователь -left-> (Статистика)
Пользователь -right-> (Поиск)


Пользователь --> (Просмотр данных)
Пользователь --> (Редактирование данных)
Пользователь --> (Удаление данных)
@enduml